default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_project_lvl2_development

test:
  <<: *default
  database: rails_project_lvl2_test

production:
  <<: *default
  database: rails_project_lvl2_production
